# Generated by Django 5.1.5 on 2025-01-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders_items', through='recommender.OrderItem', to='recommender.product'),
        ),
    ]
